### ISSUE TITLE
saas-check-in

### ISSUE THREAD

**Issue by emfeather94** [emfeather94/saas-website#1]
Hi Christina,

Here is where I am at with the saas website. I have content for all pages (the sign up page is more or less complete)

I am just trying to get the formatting/styling complete as well as making it responsive at all sizes (which is giving me some issues...) 

I will keep playing with it but may have to send some specific questions your way. Please let me know if I should send anything else.

Thanks!
Emily (group 3)

@muxlowc

**Comment by muxlowc** [comment]
@emfeather94 thats fine - thanks!
