### ISSUE TITLE
saas-help

### ISSUE THREAD

**Issue by emfeather94** [emfeather94/saas-website#2]
Hi Christina -

I am having difficulty with my header for the main page - hoping you can help me out! 

1) I am trying to get my navigation to work as it does in the modular-nav assignment we did (where the title and links align as the window gets larger). I'm not sure what I am missing but they do not align and are staggered.

2) I am trying to get the banner to look like what I have copied from my high fidelity below:

<img width="285" alt="Screen Shot 2020-04-17 at 9 22 04 AM" src="https://user-images.githubusercontent.com/55094092/79573617-e8ef6000-808c-11ea-9eed-e39d3b97d633.png">

<img width="567" alt="Screen Shot 2020-04-17 at 9 21 25 AM" src="https://user-images.githubusercontent.com/55094092/79573542-d1b07280-808c-11ea-86f9-9515c024c798.png">

The text and image are not responding the way I would like them to... Could you help me with this?

Thanks!

@muxlowc

**Comment by emfeather94** [comment]
@muxlowc 

I just realized i did not link my grid css to my index.... Will see what happens when i do that

**Comment by muxlowc** [comment]
@emfeather94 

oops, yep make sure your grid is connected. What you could also do is add the following in your main.css to the div surrounding your banner img:

    overflow: hidden;
    height: 70vh;  (vh=view height, so 70 might be too short for what you want / you can play with this as much as you want)
    width: 100%;

and you can also add a margin-top of a minus number (to you img) if you want more of the white space in the image to show

**Comment by muxlowc** [comment]
I forgot to mention that the above method would need media-queries for sizing/positioning for your image! The above should work mainly for the desktop version
