### ISSUE TITLE
saas-browser-testing

### ISSUE THREAD

**Issue by emfeather94** [emfeather94/saas-website#4]
@muxlowc

I am just testing the site on various browsing platforms/on mobile, and all are working ok except for Safari which is not displaying my fonts - forget how to fix!

Emily

**Comment by emfeather94** [comment]
@muxlowc

Also just realized one of the images I have hidden at smaller screen size is showing on mobile safari/firefox as well (and font not working on firefox mobile too).

**Comment by muxlowc** [comment]
@emfeather94 

1) hmm that's so weird. it wasn't loading for me at first, so i re-pasted from google fonts, and its working for me now?.. try the below maybe? The order of montserrat and then pacifico seemed to fix it haha

`<link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;600&family=Pacifico&display=swap" rel="stylesheet"> `

2) can you send a screenshot for the image appearing? I dont seem to see any out of place images on my end

**Comment by emfeather94** [comment]
@muxlowc 

Yay! It's working for me now haha. Thank you!

And so is the image lol. Maybe it didn't save properly or something. Anyways, all good!

Thank you :)
